<x-app-layout><x-slot name="title">Kelola Akademik</x-slot>
<div class="mb-6"><h2 class="text-lg font-semibold">Kelola Akademik</h2><p class="text-[12px] text-gray-500">Pusat pengelolaan struktur akademik dan pejabat terkait</p></div>
<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
@foreach([['Fakultas',$stats['fakultas'],'admin.fakultas.index','ti-building'],['Dekan',$stats['dekan'],'admin.dekan.index','ti-user-star'],['Program Studi',$stats['prodi'],'admin.prodi.index','ti-books'],['Kaprodi',$stats['kaprodi'],'admin.kaprodi.index','ti-user-check']] as [$label,$count,$route,$icon])
<a href="{{ route($route) }}" class="stat-card hover:border-brand"><div class="stat-icon bg-info-light text-info"><i class="ti {{ $icon }}"></i></div><div><span class="stat-label">{{ $label }}</span><span class="stat-value">{{ $count }}</span></div></a>@endforeach
</div>
<div class="grid lg:grid-cols-2 gap-6"><div class="table-card"><div class="p-4 border-b font-semibold text-[15px]">Akses Cepat</div><div class="p-4 grid sm:grid-cols-2 gap-3">@foreach([['Kelola Fakultas','admin.fakultas.index'],['Kelola Dekan','admin.dekan.index'],['Kelola Program Studi','admin.prodi.index'],['Kelola Kaprodi','admin.kaprodi.index']] as [$label,$route])<a href="{{ route($route) }}" class="p-4 border rounded-xl hover:border-brand hover:bg-blue-50 text-[13px] font-medium">{{ $label }} <i class="ti ti-arrow-right float-right"></i></a>@endforeach</div></div>
<div class="table-card"><div class="p-4 border-b flex justify-between"><div><h3 class="font-semibold text-[15px]">Program Studi</h3><p class="text-[11px] text-gray-400">Ringkasan data terbaru</p></div><a href="{{ route('admin.prodi.index') }}" class="badge badge-info">Lihat Semua</a></div><div class="divide-y">@foreach($programStudi as $prodi)<div class="p-3 flex justify-between gap-3"><div><div class="text-[13px] font-medium">{{ $prodi->nama }}</div><div class="text-[11px] text-gray-500">{{ $prodi->fakultas?->nama }} · {{ $prodi->kaprodi?->nama ?? 'Belum ada Kaprodi' }}</div></div><span class="badge badge-secondary">{{ $prodi->ormawas_count }} Ormawa</span></div>@endforeach</div></div></div>
</x-app-layout>
