services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kegiatan-app-dev
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_URL: http://localhost:${APP_PORT:-8000}
      SESSION_SECURE_COOKIE: "false"
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-ormawa_db}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-}
      UNUJA_API_BASE_URL: ${UNUJA_API_BASE_URL:-https://v2-api.unuja.ac.id}
      UNUJA_API_LOGIN_URL: ${UNUJA_API_LOGIN_URL:-https://v2-api.unuja.ac.id/log/masuk}
      UNUJA_API_USERNAME: ${UNUJA_API_USERNAME:-}
      UNUJA_API_PASSWORD: ${UNUJA_API_PASSWORD:-}
      UNUJA_API_KEY_HEADER: ${UNUJA_API_KEY_HEADER:-unujasimptapikey}
      UNUJA_API_TIMEOUT: ${UNUJA_API_TIMEOUT:-10}
      # RUN_MIGRATIONS: "true" # Opsional di dev, biasanya developer run 'php artisan migrate' manual
    ports:
      - "5173:5173" # Dibuka kembali untuk Vite (Hot Module Replacement / Live Reload)
    volumes:
      - .:/var/www/html # Bind mount: Ubah kode di komputer, langsung berubah di container
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: kegiatan-nginx-dev
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80" # Hapus 127.0.0.1 agar bisa diakses dari device lain di satu WiFi (misal HP)
    volumes:
      # Nginx mengambil aset statis (CSS/JS) langsung dari image app melalui volume bersama
      - assets_data:/var/www/html/public
      # Nginx butuh mount storage agar file upload bisa diakses
      - storage_data:/var/www/html/storage
      # File konfigurasi nginx production kamu
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: kegiatan-mysql-dev
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3306}:3306" # Menggunakan port default 3306 agar mudah konek via DBeaver / Navicat
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-ormawa_db}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql_data:
  # storage_data dan assets_data dihapus karena di development kita menggunakan Bind Mount (volume lokal)
