server {
    listen 80;
    access_log /dev/stdout;
    error_log /dev/stderr warn;

    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;
    charset utf-8;

    client_max_body_size 32m;
    error_page 413 /errors/upload-too-large.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass app:9000;

        fastcgi_connect_timeout 30s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;

        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_host;
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
