@php
    $editing = isset($lpj);
    $items = old('uraian') ? collect(old('uraian'))->map(fn($v,$i)=>(object)['uraian'=>$v,'anggaran_rencana'=>old('anggaran_rencana')[$i] ?? 0,'anggaran_realisasi'=>old('anggaran_realisasi')[$i] ?? 0,'keterangan'=>old('keterangan')[$i] ?? '']) : ($editing ? $lpj->realisasiAnggaran : collect([(object)['uraian'=>'','anggaran_rencana'=>0,'anggaran_realisasi'=>0,'keterangan'=>'']]));
@endphp
<x-app-layout>
    <x-slot name="title">{{ $editing ? 'Perbarui' : 'Buat' }} LPJ</x-slot>
    <form method="POST" enctype="multipart/form-data" action="{{ $editing ? route('lpj.update',$lpj) : route('lpj.store',$pengajuan) }}" class="space-y-6">
        @csrf @if($editing) @method('PATCH') @endif
        <div class="flex justify-between"><div><h2 class="text-lg font-semibold">{{ $pengajuan->judul_kegiatan }}</h2><p class="text-xs text-gray-500">{{ $pengajuan->ormawa->nama_ormawa }}</p></div><a href="{{ $editing ? route('lpj.show',$lpj) : route('pengajuan.show',$pengajuan) }}" class="text-sm text-gray-600">Kembali</a></div>
        @if($errors->any())<div class="bg-red-50 border border-red-200 rounded-lg p-4 text-sm text-red-700"><ul class="list-disc ml-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        @if($editing && $lpj->status === 'revisi')<div class="bg-amber-50 border border-amber-200 p-4 rounded-lg text-sm"><strong>Catatan BAUAK:</strong> {{ $lpj->catatan_verifikator }}</div>@endif
        <div class="bg-white rounded-xl border p-6 space-y-4">
            <h3 class="font-semibold">Pelaksanaan Kegiatan</h3>
            <div class="grid sm:grid-cols-2 gap-4"><div><label class="text-sm">Tanggal mulai aktual</label><input type="date" name="tanggal_pelaksanaan_mulai" required value="{{ old('tanggal_pelaksanaan_mulai',$editing ? $lpj->tanggal_pelaksanaan_mulai->format('Y-m-d') : $pengajuan->tanggal_mulai->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border-gray-300"></div><div><label class="text-sm">Tanggal selesai aktual</label><input type="date" name="tanggal_pelaksanaan_selesai" required value="{{ old('tanggal_pelaksanaan_selesai',$editing ? $lpj->tanggal_pelaksanaan_selesai->format('Y-m-d') : $pengajuan->tanggal_selesai->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border-gray-300"></div></div>
            <div><label class="text-sm">Ringkasan pelaksanaan</label><textarea name="ringkasan_pelaksanaan" required rows="4" class="mt-1 w-full rounded-lg border-gray-300">{{ old('ringkasan_pelaksanaan',$lpj->ringkasan_pelaksanaan ?? '') }}</textarea></div>
            <div><label class="text-sm">Hasil kegiatan</label><textarea name="hasil_kegiatan" required rows="4" class="mt-1 w-full rounded-lg border-gray-300">{{ old('hasil_kegiatan',$lpj->hasil_kegiatan ?? '') }}</textarea></div>
            <div class="grid sm:grid-cols-2 gap-4"><div><label class="text-sm">Jumlah peserta</label><input type="number" min="0" name="jumlah_peserta" required value="{{ old('jumlah_peserta',$lpj->jumlah_peserta ?? 0) }}" class="mt-1 w-full rounded-lg border-gray-300"></div><div><label class="text-sm">Kendala (opsional)</label><textarea name="kendala" rows="2" class="mt-1 w-full rounded-lg border-gray-300">{{ old('kendala',$lpj->kendala ?? '') }}</textarea></div></div>
        </div>
        <div class="bg-white rounded-xl border p-6">
            <div class="flex justify-between items-center mb-4"><div><h3 class="font-semibold">Realisasi Anggaran</h3><p class="text-xs text-gray-500">Total RAB: {{ $pengajuan->rab?->total_anggaran_formatted ?? 'Belum tercatat' }}</p></div><button type="button" onclick="addItem()" class="px-3 py-2 bg-gray-100 rounded-lg text-sm">+ Tambah item</button></div>
            <div id="items" class="space-y-3">@foreach($items as $item)<div class="item grid grid-cols-1 sm:grid-cols-12 gap-2 p-3 bg-gray-50 rounded-lg"><input name="uraian[]" required value="{{ $item->uraian }}" placeholder="Uraian" class="sm:col-span-3 rounded border-gray-300 text-sm"><input type="number" min="0" step="0.01" name="anggaran_rencana[]" required value="{{ $item->anggaran_rencana }}" placeholder="Rencana" class="sm:col-span-2 rounded border-gray-300 text-sm"><input type="number" min="0" step="0.01" name="anggaran_realisasi[]" required value="{{ $item->anggaran_realisasi }}" placeholder="Realisasi" class="sm:col-span-2 rounded border-gray-300 text-sm"><input name="keterangan[]" value="{{ $item->keterangan }}" placeholder="Keterangan" class="sm:col-span-4 rounded border-gray-300 text-sm"><button type="button" onclick="this.closest('.item').remove()" class="text-red-600">Hapus</button></div>@endforeach</div>
        </div>
        <div class="bg-white rounded-xl border p-6 space-y-4"><h3 class="font-semibold">Dokumen dan Bukti</h3>
            <div><label class="text-sm">Dokumen LPJ (PDF/DOC/DOCX, maks. 10 MB)</label><input type="file" name="file_laporan" @required(!$editing) accept=".pdf,.doc,.docx" class="mt-1 block w-full text-sm"></div>
            <div class="grid sm:grid-cols-3 gap-4"><div><label class="text-sm">Dokumentasi</label><input type="file" multiple name="dokumentasi[]" accept=".jpg,.jpeg,.png,.pdf" class="mt-1 block w-full text-sm"></div><div><label class="text-sm">Bukti transaksi</label><input type="file" multiple name="bukti_transaksi[]" accept=".jpg,.jpeg,.png,.pdf" class="mt-1 block w-full text-sm"></div><div><label class="text-sm">Lampiran lainnya</label><input type="file" multiple name="lampiran_lainnya[]" class="mt-1 block w-full text-sm"></div></div>
            @if($editing && $lpj->lampiran->isNotEmpty())<div class="space-y-2">@foreach($lpj->lampiran as $file)<div class="flex justify-between text-sm border rounded p-2"><a target="_blank" class="text-brand" href="{{ $file->file_url }}">{{ $file->nama_file }}</a><button form="delete-file-{{ $file->id }}" class="text-red-600">Hapus</button></div>@endforeach</div>@endif
        </div>
        <div class="flex justify-end gap-3"><button name="aksi" value="draft" class="px-5 py-2.5 bg-gray-100 rounded-lg text-sm font-medium">Simpan Draft</button><button name="aksi" value="ajukan" class="px-5 py-2.5 bg-brand text-white rounded-lg text-sm font-medium">Ajukan ke BAUAK</button></div>
    </form>
    @if($editing)@foreach($lpj->lampiran as $file)<form id="delete-file-{{ $file->id }}" method="POST" action="{{ route('lpj.lampiran.destroy',[$lpj,$file]) }}">@csrf @method('DELETE')</form>@endforeach @endif
    <script>function addItem(){document.getElementById('items').insertAdjacentHTML('beforeend',`<div class="item grid grid-cols-1 sm:grid-cols-12 gap-2 p-3 bg-gray-50 rounded-lg"><input name="uraian[]" required placeholder="Uraian" class="sm:col-span-3 rounded border-gray-300 text-sm"><input type="number" min="0" step="0.01" name="anggaran_rencana[]" required placeholder="Rencana" class="sm:col-span-2 rounded border-gray-300 text-sm"><input type="number" min="0" step="0.01" name="anggaran_realisasi[]" required placeholder="Realisasi" class="sm:col-span-2 rounded border-gray-300 text-sm"><input name="keterangan[]" placeholder="Keterangan" class="sm:col-span-4 rounded border-gray-300 text-sm"><button type="button" onclick="this.closest('.item').remove()" class="text-red-600">Hapus</button></div>`)};</script>
</x-app-layout>
