<x-app-layout>
    <x-slot name="title">Detail LPJ</x-slot>
    <div class="flex flex-col sm:flex-row justify-between gap-3 mb-6"><div><h2 class="text-lg font-semibold">{{ $lpj->pengajuan->judul_kegiatan }}</h2><p class="text-xs text-gray-500">{{ $lpj->pengajuan->ormawa->nama_ormawa }}</p></div><div class="flex gap-2">
        @if(in_array(auth()->user()->role,['ormawa','mahasiswa']) && in_array($lpj->status,['draft','revisi']))<a href="{{ route('lpj.edit',$lpj) }}" class="px-4 py-2 bg-brand text-white rounded-lg text-sm">Perbarui LPJ</a>@endif
        <a href="{{ route('lpj.index') }}" class="px-4 py-2 bg-gray-100 rounded-lg text-sm">Kembali</a></div></div>
    @if(session('success'))<div class="mb-4 p-3 bg-green-50 text-green-700 rounded-lg text-sm">{{ session('success') }}</div>@endif
    <div class="grid lg:grid-cols-3 gap-6"><div class="lg:col-span-2 space-y-6">
        <div class="bg-white border rounded-xl p-6"><div class="flex justify-between mb-5"><h3 class="font-semibold">Pelaksanaan</h3><span class="badge {{ $lpj->status === 'diterima' ? 'badge-success' : ($lpj->status === 'ditolak' ? 'badge-danger' : 'badge-warning') }}">{{ $lpj->status_label }}</span></div>
            <dl class="grid sm:grid-cols-2 gap-4 text-sm"><div><dt class="text-gray-500">Pelaksanaan aktual</dt><dd class="font-medium">{{ $lpj->tanggal_pelaksanaan_mulai->format('d M Y') }} – {{ $lpj->tanggal_pelaksanaan_selesai->format('d M Y') }}</dd></div><div><dt class="text-gray-500">Jumlah peserta</dt><dd class="font-medium">{{ number_format($lpj->jumlah_peserta) }} orang</dd></div></dl>
            <div class="mt-5"><p class="text-xs uppercase text-gray-500 font-semibold">Ringkasan</p><p class="mt-1 text-sm whitespace-pre-line">{{ $lpj->ringkasan_pelaksanaan }}</p></div><div class="mt-5"><p class="text-xs uppercase text-gray-500 font-semibold">Hasil</p><p class="mt-1 text-sm whitespace-pre-line">{{ $lpj->hasil_kegiatan }}</p></div>@if($lpj->kendala)<div class="mt-5"><p class="text-xs uppercase text-gray-500 font-semibold">Kendala</p><p class="mt-1 text-sm whitespace-pre-line">{{ $lpj->kendala }}</p></div>@endif
        </div>
        <div class="bg-white border rounded-xl p-6"><h3 class="font-semibold mb-4">Rencana dan Realisasi Anggaran</h3><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="text-left p-3">Uraian</th><th class="text-right p-3">Rencana</th><th class="text-right p-3">Realisasi</th><th class="text-right p-3">Selisih</th></tr></thead><tbody class="divide-y">@foreach($lpj->realisasiAnggaran as $item)<tr><td class="p-3">{{ $item->uraian }}<div class="text-xs text-gray-500">{{ $item->keterangan }}</div></td><td class="p-3 text-right">Rp {{ number_format($item->anggaran_rencana,0,',','.') }}</td><td class="p-3 text-right">Rp {{ number_format($item->anggaran_realisasi,0,',','.') }}</td><td class="p-3 text-right">Rp {{ number_format($item->anggaran_rencana-$item->anggaran_realisasi,0,',','.') }}</td></tr>@endforeach</tbody><tfoot class="font-semibold bg-gray-50"><tr><td class="p-3">Total</td><td class="p-3 text-right">{{ $lpj->pengajuan->rab?->total_anggaran_formatted ?? '-' }}</td><td class="p-3 text-right">Rp {{ number_format($lpj->realisasi_anggaran,0,',','.') }}</td><td class="p-3 text-right">Rp {{ number_format($lpj->sisa_anggaran,0,',','.') }}</td></tr></tfoot></table></div></div>
    </div><div class="space-y-6">
        <div class="bg-white border rounded-xl p-5"><h3 class="font-semibold mb-3">Dokumen</h3><a href="{{ $lpj->file_url }}" target="_blank" class="block p-3 bg-gray-50 rounded-lg text-sm text-brand"><i class="ti ti-file-text mr-2"></i>Dokumen LPJ terbaru</a>@if($lpj->versiDokumen->count() > 1)<p class="text-xs font-semibold text-gray-500 mt-4 mb-2">RIWAYAT VERSI</p>@foreach($lpj->versiDokumen as $versi)<a href="{{ $versi->file_url }}" target="_blank" class="block mt-2 text-xs text-brand">Versi {{ $versi->versi }} · {{ $versi->nama_file }}</a>@endforeach @endif @foreach($lpj->lampiran as $file)<a href="{{ $file->file_url }}" target="_blank" class="block mt-2 p-3 bg-gray-50 rounded-lg text-sm text-brand"><i class="ti ti-paperclip mr-2"></i>{{ $file->nama_file }}<span class="block text-xs text-gray-500">{{ str_replace('_',' ',$file->jenis) }}</span></a>@endforeach</div>
        @if($lpj->catatan_verifikator)<div class="bg-amber-50 border border-amber-200 rounded-xl p-5"><h3 class="font-semibold mb-2">Catatan BAUAK</h3><p class="text-sm">{{ $lpj->catatan_verifikator }}</p></div>@endif
        @if(auth()->user()->isBauak() && $lpj->status === 'diajukan')<div class="bg-white border rounded-xl p-5"><h3 class="font-semibold mb-3">Keputusan BAUAK</h3><form method="POST" action="{{ route('bauak.lpj.decide',$lpj) }}" class="space-y-3">@csrf<textarea name="catatan" rows="4" placeholder="Catatan pemeriksaan..." class="w-full rounded-lg border-gray-300 text-sm"></textarea><div class="grid grid-cols-3 gap-2"><button name="status" value="revisi" class="py-2 bg-amber-500 text-white rounded text-xs">Revisi</button><button name="status" value="ditolak" class="py-2 bg-red-600 text-white rounded text-xs">Tolak</button><button name="status" value="diterima" class="py-2 bg-green-600 text-white rounded text-xs">Terima</button></div></form></div>@endif
        @if($lpj->riwayatVerifikasi->isNotEmpty())<div class="bg-white border rounded-xl p-5"><h3 class="font-semibold mb-3">Riwayat Verifikasi</h3>@foreach($lpj->riwayatVerifikasi as $item)<div class="border-l-2 pl-3 mb-4 text-sm"><p class="font-medium capitalize">{{ $item->status }} · {{ $item->user->nama }}</p><p class="text-xs text-gray-500">{{ $item->tanggal_verifikasi->format('d M Y H:i') }}</p>@if($item->catatan)<p class="mt-1">{{ $item->catatan }}</p>@endif</div>@endforeach</div>@endif
    </div></div>
</x-app-layout>
